import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/common";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} container m-auto grid min-h-screen grid-rows-[auto_1fr_auto] gap-8 px-4 font-sans`}
      >
        <Header />
        {children}
        <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center">
          Hecho por Franquito
        </footer>
      </body>
    </html>
  );
}
